### PR TITLE
added sitemap receipe

### PR DESCRIPTION
**Pull request by itlackey**
Added an example of generating a sitemap.xml file for a static site using a gulp plugin. Thought this might be helpful to further illustrate the relationship between gulp and assemble.

### CODE REVIEW

**Comment by stefanwalther** [comment]
Thx, could you please also add a test, thx.

**Comment by itlackey** [comment]
Never used Chai, but will give it a shot. :)

**Comment by itlackey** [comment]
I merged with your latest changes and added some tests for the new recipe. The one collection test is still failing but the tests I add appear to pass. I also updated from using gulp-ext to gulp-extname in my recipes.

**Comment by stefanwalther** [comment]
OK, thx, will have a look into it.

**Pull request merged**
